### ISSUE TITLE
Document how we communicate

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#103]
When should we use email or Hipchat or Jira or Github or Hangouts or something else?

**Comment by huberfl** [comment]
@lewisnyman, Fredrik and I have put some content together in the past. It might be of use here: https://docs.google.com/a/flink-solutions.de/document/d/1r5nua_AZcTNeUbUV_uBZB0NrzPZHz_l9Qg1O9oMijn8/edit?usp=sharing and https://docs.google.com/a/wunderkraut.com/document/d/1hXt1FIfPJNfLMUzTYH7NujNr0a8QlEi0tQjxidcLHy4/edit?usp=sharing

**Comment by lewisnyman** [comment]
This looks great! Maybe you could start with a pull request to move this into the Wunder Way? Happy to review.

**Comment by huberfl** [comment]
Sure. I have started a new branch in my repo and will create a PR upon the finalization of the first version.

**Comment by joesb** [comment]
I think this is closed by #107 - true?

**Comment by huberfl** [comment]
@joesb, yes. Should I have reference 103 in the PR?

**Comment by joesb** [comment]
Great, good news.

GitHub does have a special syntax for closing issues from Pull Requests (I keep forgetting to use it myself, too!):
https://github.com/blog/1506-closing-issues-via-pull-requests
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by huberfl** [comment]
Thanks

On Wed, Aug 19, 2015 at 12:40 PM Joe Baker <notifications@github.com> wrote:

> Great, good news.
>
> GitHub does have a special syntax for closing issues from Pull Requests (I
> keep forgetting to use it myself, too!):
> https://github.com/blog/1506-closing-issues-via-pull-requests
> https://help.github.com/articles/closing-issues-via-commit-messages/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wunderkraut/WunderWay/issues/103#issuecomment-132535335>
> .
>
-- 

________
Florian Huber - Project Manager, Wunderkraut Germany
florian.huber@wunderkraut.com // phone +49.179.4698130

Wunderkraut. Working wonders with Drupal – http://wunderkraut.com/

Wunderkraut GmbH, MTZ D1.019, Agnes-Pockels-Bogen 1, D-80992 München
HRB191094 Amtsgericht München, Geschäftsführer: Reinhard Gloggengiesser,
Daniel Nolde
