### ISSUE TITLE
Update Equipment page - IKEA are now selling standing desks

### ISSUE THREAD

**Issue by joesb** [wunderkraut/WunderWay#111]
Update the Standing desks section of the Equipment page at http://way.wunder.io/working-at-wunderkraut/health-and-safety/work-comfortably/equipment/ with links to IKEA's sit/stand desks

http://www.ikea.com/gb/en/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/de/de/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/fi/fi/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/be/fr/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/be/nl/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/nl/nl/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/se/sv/catalog/categories/departments/workspaces/18962/
http://www.ikea.com/no/no/catalog/categories/departments/workspaces/18962/

(Can't find a link for Latvia or Estonia - is IKEA not there?)

**Comment by joesb** [comment]
When I added country links I just used the pipe symbol to separate them, to take up as little vertical space as possible and drop any sense of hierarchy, but discovered that Jekyll interpreted that format, pipe separation, as a table.

Any thoughts on that as a display format when trying to remove the UK-centric legacy of WunderWay?

**Comment by lewisnyman** [comment]
Would square brackets work?

On Wednesday, 19 August 2015, Joe Baker <notifications@github.com> wrote:

> When I added country links I just used the pipe symbol to separate them,
> to take up as little vertical space as possible and drop any sense of
> hierarchy, but discovered that Jekyll interpreted that format, pipe
> separation, as a table.
>
> Any thoughts on that as a display format when trying to remove the
> UK-centric legacy of WunderWay?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wunderkraut/WunderWay/issues/111#issuecomment-132558539>
> .
>


-- 
Lewis Nyman
+447753103690
lewisnyman.co.uk <http://www.lewisnyman.co.uk>
@lewisnyman <http://twitter.com/lewisnyman>

**Comment by joesb** [comment]
Yep, square brackets are fine. 

The MD table format auto-aligns to avoid a line wrap, but doesn't quite feel like the right method for displaying this. Square-brackets are uglier display, but it works fine.
