### ISSUE TITLE
Create a 'remote working' page

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#12]

**Comment by oxyc** [comment]
Bump. I'd be interested in reading it before sending an application :grinning:

**Comment by huberfl** [comment]
I have gathered some input on how to improve the speed of the bonding process of a remote team. Bottom line:
* put the team (including the customer) in one place for the first week(s) of the project
* celebrate milestones and events
* facetime, facetime, facetime (and if it's just by video)

**Comment by joesb** [comment]
Closed by merging #86
