### ISSUE TITLE
Rethink the WunderWay IA

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#16]
The Who, How, Why sections are too vague and unbalanced.

**Comment by steveparks** [comment]
How about...

Our Brand
Our Clients
Our Team
Our Tools

As the top level items?

Then the secondary levels could expand. Eg 'Our Tools' could include:
 - Software
 - Expertise
 - Processes

**Comment by lewisnyman** [comment]
Alex's content review - https://docs.google.com/spreadsheets/d/116NxfQzUJjAOiKbqe-aws-6a5Q5eEJuzM2-vR2_PjIw/edit#gid=1986152902
First draft - http://bquniy.axshare.com/#p=introduction

**Comment by lewisnyman** [comment]
Some inspiration:
https://www.wearesantander.co.uk/documents/16600/7215102/Employee+Handbook+09.12.13
http://us.boehringer-ingelheim.com/content/dam/internet/opu/us_EN/documents/careers/eehandbk_june_09.pdf

**Comment by steveparks** [comment]
Some other inspiration...
https://www.valvesoftware.com/company/Valve_Handbook_LowRes.pdf

**Comment by steveparks** [comment]
Another thought...
Could we somehow align the sections with the aspirations, strategy or behaviours in our branding? Would show how it all fits together, and reinforce what we're about.

**Comment by lewisnyman** [comment]
We could try, I think it's a good idea to try and bake elements of the brand into the content instead of keeping it hidden away on a page no one reads. 

Do you have a suggestion for we could base a structure around them? I imagine the broadness of the words could make it harder to find your way around. Is it clear. The principles are all aligned to how we do things, not what we do. I'm trying to imagine which heading "buying hardware" would fall under.

It might work as a structure for the orientation page, which is more linear, and would be a good place to introduce the principles.

**Comment by WunderLemon** [comment]
There may be some aspects of branding vocabulary we can bring into section names but, like Lewis, I think it's better to keep naming familiar. Content is the best place for expressing branding in a natural, believable way.

I also agree about an orientation page being a good place for elucidating principles and explaining Wunderers can live by them in their everyday work.
