### ISSUE TITLE
ISO9001: Simplify Project Folder Structure

### ISSUE THREAD

**Issue by huntons** [wunderkraut/WunderWay#183]
I suggest that we simplify the folder structure in line with what we've actually been using. It'll make it far easier to find files and documents. Amend to:

Project Name
    > Commercials
    > Issues & Risks
    > Meetings
    > Reviews
    > Slides Template
    > Supporting Docs
    > UX & Design

**Comment by huberfl** [comment]
I am in strong favor of simplification and like the new layout, which only has one level as a starting point.
I could imagine some refinements:
* renaming "Slides Template" to "Templates" and place any template here.
* "Supporting Docs" sounds a little bit like "other documentation". Can you specify this in more detail, please?
* can we add a section "Developer Documentation" and / or "Support & Maintenance"?

**Comment by huntons** [comment]
Thanks @floretan At the moment this is not for WunderWay, it's just for our ISO system in the UK but it's worth considering in the context of WunderWay too. I'll raise a separate issue for that
