### ISSUE TITLE
Document the process for add/changing wunderway content

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#23]
I think we should move to a pull request workflow, as all changes need to be peer reviewed and discussed

**Comment by steveparks** [comment]
All looks like a good plan. There are some typos to be fixed, but I'm not sure about how to edit those when this is just a pull request?

**Comment by lewisnyman** [comment]
You can view the changes, make comments per line, and edit typos in this view: https://github.com/wunderkraut/WunderWay/pull/40/files

You should see an edit button but each file like you do in the repository file browser. Also see: https://help.github.com/articles/using-pull-requests/#reviewing-the-pull-request

**Comment by lewisnyman** [comment]
I can write more documentation about how to review PRs but I thought linking to Githubs own documentation was enough

**Comment by steveparks** [comment]
Ah yes - you’re right.

I got lost in the meta maze here. I just proof read the text, and didn’t follow the links in it, to find the steps to edit the text within the pull request… if you see what i mean ;)

Will follow steps later








—Steve Parks

Director, Consultant

Wunder UK




http://www.wunder.uk

Nurturing Growth and Success in Digital Business
