### ISSUE TITLE
Wundertalk about WunderWay tool?

### ISSUE THREAD

**Issue by mikaelkundert** [wunderkraut/WunderWay#36]
We have people who are new to WunderWay tool. It would be nice to show this tool and create an crash course how to maintain content on it especially for people in administration.

I can think of at least following topics:
* GitHub Issues
* GitHub Pull Requests
* What is technical and what is content in the repo
* How to code markdown + is there tools to preview it (or even better GUI tools for maintaining content?)

**Comment by lewisnyman** [comment]
This is a good idea, I hope we can flesh out [this page](http://way.wunder.io/how/how-edit-wunderway/) a lot and base the wundertalk on that, as soon as we are agreed on the new PR-based workflow

**Comment by lewisnyman** [comment]
Steve H did this last friday: https://www.youtube.com/watch?v=Hr9aByLra9s&feature=youtu.be
