### ISSUE TITLE
Updated IA seems to have broken links

### ISSUE THREAD

**Issue by steveparks** [wunderkraut/WunderWay#50]
On the page at http://way.wunder.io/working-with-clients/

The links to pages no longer work, returning a 404.

I guess that the changes brought in for the new IA may have affected the way paths are generated.

**Comment by steveparks** [comment]
So pages did have the first part of the path as 'clients/'
But it should now be 'working-with-clients/' 
on all links in the client section

**Comment by lewisnyman** [comment]
Yep, there could be a few broken links around the place as we've changed a
lot of paths.

On Monday, 8 June 2015, Steve Parks <notifications@github.com> wrote:

> So pages did have the first part of the path as 'clients/'
> But it should now be 'working-with-clients/'
> on all links in the client section
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wunderkraut/WunderWay/issues/50#issuecomment-109955982>
> .
>


-- 
Lewis Nyman
+447753103690
lewisnyman.co.uk <http://www.lewisnyman.co.uk>
@lewisnyman <http://twitter.com/lewisnyman>

**Comment by lewisnyman** [comment]
Closing this in favour of individual issues
