### ISSUE TITLE
Create a section on staying healthy at work

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#57]
I received  lot of great tips and information from https://twitter.com/RonaiBrumett at the Twin Cities Drupal Camp. She said she was going to send me an email with loads of easily digestible information. I'd really like to share this with the group.

**Comment by huntons** [comment]
I've recently started a page for this - http://way.wunder.io/working-at-wunderkraut/wunder-fitness/

**Comment by lewisnyman** [comment]
@huntons Ah nice, do you mind if I build it into multiple sections? Do you think 'WunderFitness' is a sub-section of 'staying healthy at work'? I don't want people to think the whole section is about running.

**Comment by huntons** [comment]
Yes, this all ties in with the "great reasons to work here" conversation. We should be clear that it's about walking, running, cycling, swimming. FlorianH even counts his pressups!

**Comment by joesb** [comment]
… yes, and eating healthily, taking regular breaks, some working practice options like standing desks, ergonomic keyboards maybe, etc etc

**Comment by huntons** [comment]
It's a good chance to include some nice pics in the section to show our home office setups, explain the benefits of each etc
