### ISSUE TITLE
Create a page about sharing passwords securely

### ISSUE THREAD

**Issue by joesb** [wunderkraut/WunderWay#58]
E.g. a workflow using 1Password:

- Exported .agilekeychain vault file in a Wunder GoogleDrive space
- synced between colleagues with GoogleDrive app
- need vault password to unlock, which can store in personal 1Password vault
- etc.

Other options for doing it? e.g. with Lastpass?

**Comment by huberfl** [comment]
An alternative approach: 
* Dropbox folder with encrypted files in it
* use encfs to mount it and read the files

This solution is supported well in Linux, which is a requirement

**Comment by steveparks** [comment]
A key criteria for this is ease of use by non-technical colleagues

**Comment by jcnventura** [comment]
Both suggestions above (1password or encfs) can use both Google Drive and Dropbox interchangeably.

**Comment by reinhardweber** [comment]
We need clear acceptance criteria for the solution. I have created a first draft at https://goo.gl/3ioDGF.
Pls check if they also reflect yours. Feel free to comment/add/edit there so we get a clearer picture what we really want and need.

**Comment by james-nesbitt** [comment]
Please consider the various p2p options, that require no server or 3rd party service:

(most options use libtorrent to distribute a folder amongst a group)

1. syncthing: OSS, written in go,  (https://syncthing.net/)
2. torrentsync: Not so open source, has a paid option, very polished (https://www.getsync.com/)

PROs:
- OSS solutions avaialble;
- Potentially no 3rd party involvement required;
- No data kept anywhere outside of the team;
- Any file/folder based data can be piggybacked.

CONs:
- may not need some of Reinhard's security requirements (Access control)
- requires local storage;
- if all teammates leave, then data may get lost.

**Comment by joesb** [comment]
Right, I'm going to tackle writing this today. My approach is to **just write something** and then we can improve it iteratively subsequently.

MVP » Iterate.

I agree with @reinhardweber that we could do with a thorough discussion, but I don't think we need to wait for a conclusion to that discussion before getting some helpful suggestions in place - and once we *do* have some conclusions from that discussion we can amend, update and improve the WW page.

I also completely agree with @steveparks that we need to make sure there's a viable way of doing this that both ensures security *and* ease of use by non-technical colleagues - even if that means several alternatives.

Thanks for all the contributions so far - all very useful, and I'll incorporate all suggestions (somehow!)
