### ISSUE TITLE
WunderExperts Groups

### ISSUE THREAD

**Issue by huntons** [wunderkraut/WunderWay#63]
We need a page to list who is involved in each expert group so that people in each country know who to turn to if they have a specific question or if they want to talk through a new idea or initiative

**Comment by joesb** [comment]
Nice idea.

The 'Technology Taskforce' group is:

* Florian Lorétan
* Tomi Mikola
* Joe Baker
* Teemu Merikoski
* Miķelis Zaļais
* Dieter Beheydt
* Tomas Persson
* Ardi Hundt

**Comment by joesb** [comment]
I think this was closed by #64 
http://way.wunder.io/about-this-site/wunder-experts-groups/
