### ISSUE TITLE
Migrate the hipchat documentation to the wunderway

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#65]
https://docs.google.com/document/d/18R-RglYUJuLOYT-D2LxbtxkTLQNBlNB1Vf91SwbLA8c/edit#heading=h.f5f60flholid

**Comment by huntons** [comment]
Where do you propose we link to this from?

**Comment by lewisnyman** [comment]
http://way.wunder.io/working-at-wunderkraut/communicating/

**Comment by huntons** [comment]
Go for it!

**Comment by huberfl** [comment]
Shall we just link the document or integrate the whole into the WunderWay, @huntons?

**Comment by huntons** [comment]
Because it's not a big document and it's relevant to all Wunderers then I'd suggest we create a new page for this on WunderWay. That way we keep all of the content in one place.

**Comment by huberfl** [comment]
Actually, #118 has duplicated this issue. Hence, it can be marked done, @huntons
