### ISSUE TITLE
All links on "http://way.wunder.io/working-at-wunderkraut/new-starter/" are broken.

### ISSUE THREAD

**Issue by marcusx** [wunderkraut/WunderWay#71]
The following links are broken:
- http://way.wunder.io/how/new-starter/buddies/
- http://way.wunder.io/how/sip-phone-setup/
- http://way.wunder.io/how/how-claim-expenses/
- http://way.wunder.io/how/fridays/
- and all other links on this page

**Comment by joesb** [comment]
I'll take a stab at this

**Comment by joesb** [comment]
Aah, already closed.
