### ISSUE TITLE
Right click is deactivate in the whole wunderway docs.

### ISSUE THREAD

**Issue by marcusx** [wunderkraut/WunderWay#74]
Is there a reason that copy & paste is not allowed? Especially in the snippets section this makes no sense from my perspective.

**Comment by lewisnyman** [comment]
@marcusx Are you able to give me more information to recreate this? Which page were you on? Which browser/OS are you using? Right click seems to work for me.

**Comment by marcusx** [comment]
@lewisnyman weird. I can't reproduce it either. I used chrome on OSX and couldn't fix it by restarting Chrome yesterday. But it seems to be healed overnight. I will reopen the issue if I see it again.
