### ISSUE TITLE
Enhance WunderWay editing on local computer

### ISSUE THREAD

**Issue by huberfl** [wunderkraut/WunderWay#83]
We need to add some more information on how to edit the WunderWay on a local computer. If we consider contributors without permissions, they might need to fork the WunderWay and follow the pull request workflow.
Also an interesting input with this regards: 
> Never Commit On Master
> When you're working on a fork, you should always think of your master branch as a "landing place" for upstream changes. You should only ever make your commits to topic branches, and your own commits should only ever end up on master after they've been merged in upstream by a maintainer.
> This is really for your own convenience: it's easy for the maintainer of a project to accept your pull request from your master branch, but it's problematic for your fork when you want to pull the changes back and your master branch has diverged from upstream's master branch.
> https://contribute.jquery.org/commits-and-pull-requests/

**Comment by lewisnyman** [comment]
Yep, all contributors should follow the PR workflow. We only have some exceptions for those who have permissions to fix typos etc.

The aim is for Wunderway to be editable by someone with non-technical experience. Do you think there is an easy way to explain this without going into the details of how to use Git effectively?

**Comment by huberfl** [comment]
The easiest way is to edit it in Github, as you have already described it.
If someone wants to have the option for offline editing then there is
hardly a way around the fork-branch-commit-pr workflow. But these are
steps, which can be described fairly straightforward. And there are always
tech people around to help with the start.
Here, it might make sense to offer local WunderWay editing bootcamps.
Lewis Nyman <notifications@github.com> schrieb am So., 19. Juli 2015 um
19:50:

> Yep, all contributors should follow the PR workflow. We only have some
> exceptions for those who have permissions to fix typos etc.
>
> The aim is for Wunderway to be editable by someone with non-technical
> experience. Do you think there is an easy way to explain this without going
> into the details of how to use Git effectively?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wunderkraut/WunderWay/issues/83#issuecomment-122688587>
> .
>
-- 

________
Florian Huber - Project Manager, Wunderkraut Germany
florian.huber@wunderkraut.com // phone +49.179.4698130

Wunderkraut. Working wonders with Drupal – http://wunderkraut.com/

Wunderkraut GmbH, MTZ D1.019, Agnes-Pockels-Bogen 1, D-80992 München
HRB191094 Amtsgericht München, Geschäftsführer: Reinhard Gloggengiesser,
Daniel Nolde

**Comment by joesb** [comment]
@huberfl Are you saying that the description of editing the WunderWay on a local computer on http://way.wunder.io/about-this-site/how-edit-wunderway/ need adapting?

**Comment by huberfl** [comment]
Yes, @joesb.

**Comment by huberfl** [comment]
Provide a short checklist / or enhance the step-by-step for editing the WunderWay in a fork and local branch.
This should also cover the Issue- / PullRequest-workflow and give advise on specialties (e.g. keywords to close issues)
References:

https://github.com/blog/1506-closing-issues-via-pull-requests
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by huberfl** [comment]
@joesb and @lewisnyman, do you agree that the current description on http://way.wunder.io/about-this-site/how-edit-wunderway/ about _Editing The WunderWay On Your Local Computer using the Github app_ needs adaption in step 7 and about how to update your local fork?
In general, I think it should look like this (replacing the numbered items starting from 6.):
6. Create a new branch to store/commit your local changes to
7. Open your text editor. From the File menu choose ‘Open…’. Select the folder where you cloned the WunderWay repository.
8. In Sublime and similar text editors, you’ll see the folder structure of the WunderWay on the left hand side. Find the file you want to edit, and make the changes. Select File>Save when you are done.
9. In the Github for Mac application, under ‘changes’ it will show that you have ‘uncommitted changes’. Type a heading and description about the changes you made. Click Commit.
10. You can make many edits like this offline. When you are back online and want to open a pull request for your changes you follow the instructions on Create Pull Requests with GitHub for Mac
11. Your pull request will appear on the WunderWay pull requests page.
12. A notification of this pull request will appear in the WunderCafe Hipchat room. Reach out to specific people to ensure they see your pull request.

Then we would need a section on updating your fork and cleaning up your branches:
1. After your pull request has been accepted and merged, you need to update your local clone by using git pull upstream master (assuming that the remote has been called _upstream_).
2. By this your local repository’s master branch will have your feature branch’s changes committed. 
3. Now you can delete your feature branch: git branch -d <branch name>
4. And update your master branch in the forked repository: git push origin master
5. Finally, push the deletion of the feature branch to your GitHub repository: git push --delete origin <branch name>

**Comment by huberfl** [comment]
I think that we can close this issue, because it was addressed in PR #160
