### ISSUE TITLE
Jira: Document how to set a new project, users, assign roles

### ISSUE THREAD

**Issue by huberfl** [wunderkraut/WunderWay#87]
WK DE is using primarily Jira and the knowledge is mostly with me.
I want to document how to
* create new projects
* assign our default workflows (Scrum or Kanban)
* create new users (Wunderkraut and customers/external)
* assign appropriate permissions

**Comment by huntons** [comment]
@huberfl this is the first example where we need to add country specific content. I'd suggest we have a small section on this page - http://way.wunder.io/delivering-projects/backlogs-and-planning/ - that links to setting up Rally, Jira and any other country specific tools. That way we keep it all in context and it's easy to update as other countries add their content. Any thoughts @lewisnyman ?

**Comment by lewisnyman** [comment]
Yep, let's create two sub pages. One for Rally and one for Jira. They can follow a similar heading structure and then it's easy to link to the same subsection on the two pages.

@huberfl, do you want to create the Jira page under the delivering-projects folder. @huntons Then you can create a Rally page that follows the same structure?

**Comment by huntons** [comment]
Yes, I'll create that page and will link to both from the http://way.wunder.io/delivering-projects/backlogs-and-planning/ page.

**Comment by huberfl** [comment]
@lewisnyman, yes, I will do.
Thanks @huntons!

**Comment by joesb** [comment]
Closed by pull request review and merge.
